version: "3.9"
services:
  web:
    image: foodtrans-auth:1.1
    ports:
      - "8088:80"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    ports:
      - 5454:5432
    environment:
      POSTGRES_USER: kunik
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kunik-db
    volumes:
      - food-trans-db:/var/lib/postgresql/data
    
  adminer:
    image: adminer
    ports:
      - "8082:8080"

volumes:
  food-trans-db:
    external: false