@host=https://localhost:7177

POST {{host}}/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhc2NoYXdyeiIsImp0aSI6Ijc4ZDhmMTlmLWVkNzctNDRmNy05NWJhLTE2ZjNjMGU0NmQ5MyIsImVtYWlsIjoiYXNjaHdhcnpAbzIucGwiLCJ1aWQiOiI0MjVjMWYxMi01MjdlLTQ4ZGEtYmI5NS1mMzJjYzg4ODdlYjciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwiZXhwIjoxNjcxNjk4MDA1LCJpc3MiOiJmb29kdHJhbnMtYXV0aCIsImF1ZCI6ImZvb2R0cmFucy1jb3JlIn0.wlo-RMnyLOaLd-pqJILN0FsXJwPl_CsXoVrNbADj9Ws