@host=https://localhost:7177

GET {{host}}/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhc2NoYXdyeiIsImp0aSI6IjMyZjhiYWQ3LTYzMjgtNGM1OC05ZTAyLTU1M2VkN2I0NTk2NyIsImVtYWlsIjoiYXNjaHdhcnpAbzIucGwiLCJ1aWQiOiI0MjVjMWYxMi01MjdlLTQ4ZGEtYmI5NS1mMzJjYzg4ODdlYjciLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwiZXhwIjoxNjcxNjkyNTY2LCJpc3MiOiJmb29kdHJhbnMtYXV0aCIsImF1ZCI6ImZvb2R0cmFucy1jb3JlIn0.K18H-yp95FxcMopU5Af0rlhN-rDP4W8i8Sgbv_1PLRE