@host=https://localhost:7177

GET {{host}}/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXRtYXQxMiIsImp0aSI6IjM3NDZhMTliLWEzYWUtNGY2Yy04OTg5LTk1OTgxNmJkYzEwNiIsImVtYWlsIjoicGF0bWF0MTJAbzIucGwiLCJ1aWQiOiI3MzFhZWRiYS02NDA3LTQxMjgtYTNkNC01ZTliZTEwNGMzZWMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwiZXhwIjoxNjcwMDc3Mzg0LCJpc3MiOiJmb29kdHJhbnMtYXV0aCIsImF1ZCI6ImZvb2R0cmFucy1jb3JlIn0.V044skS06HVARM0PGqJ8ehib9sRMrAZtZ5PQnL1D3aE