@host=https://localhost:7177

GET {{host}}/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwYXRtYXQxMiIsImp0aSI6ImY1MmRmODFkLWIzNzMtNDMxYy04MTc5LWUxYjE0ZDA3YmM3ZCIsImVtYWlsIjoicGF0bWF0MTJAbzIucGwiLCJ1aWQiOiJkYTIyMzdmZS1iNjI1LTRlOGMtYWQ4MS0xN2NiODk3NTBmNWYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwiZXhwIjoxNjcwMTAzMTI4LCJpc3MiOiJmb29kdHJhbnMtYXV0aCIsImF1ZCI6ImZvb2R0cmFucy1jb3JlIn0.2FbjUzoh4IQTuf5r9YZgSx_r7v-0jkv2oefbNgrPOuY