@host=https://localhost:7177

POST {{host}}/api/auth/register
Content-Type: application/json

{
    "firstName": "Adam",
    "lastName": "Schawrz",
    "username": "aschawrz",
    "email": "aschwarz@o2.pl",
    "password": "Pa$$word1"
}